### PR TITLE
feat: add target option

### PR DESCRIPTION
**Pull request by ghost**
Add `target` option.
This allows to skip publish or publish the extension as [public or private](https://support.google.com/chrome/a/answer/2714278?visit_id=638024663026529077-2572328455&rd=1).
This implementation is similar to what [one of semantic-release plugins](https://github.com/GabrielDuarteM/semantic-release-chrome#publish-parameters) does.

`chrome-webstore-upload@0.2.2` supports `trustedTesters` - https://github.com/fregante/chrome-webstore-upload/tree/v0.2.2#publish-extension

### CODE REVIEW

**Comment by ghost** [comment]
@bcanseco

Could you please take a look and let me know, if we can publish a new version including these changes?
I am using this plugin in webpack configuration and my goal is to publish some extensions as private.

I have also changed build configuration, because the build did not work with the `stable` (18) version.
Node 6 does not work either. All versions from 8 to 16 work fine.

```
$ nvm install 18
node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
The command "npm config set spin false" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by ghost** [comment]
@dpopp07 @jmeis @ChuckCox @padamstx
Could you please help with getting this released if @bcanseco is not available?

**Comment by dpopp07** [comment]
@kovalskyi I'm not sure I can be of any help - I'm not familiar with this project at all.

**Comment by bcanseco** [comment]
Hey @kovalskyi, sadly I don't work for IBM anymore and as such have lost write access to this repository. You're probably better off maintaining your own fork unless someone at IBM can grant access. 😞

**Pull request closed without merging**
